#!/bin/bash

ip=$(curl --silent https://checkip.amazonaws.com)
mycidr="${ip}"/32

for group in $(aws ec2 describe-security-groups | jq -r '.SecurityGroups[].GroupId')
  do
    for cidr in $(aws ec2 describe-security-groups --group-ids "${group}" | jq -r '.SecurityGroups[].IpPermissions[] | select(.FromPort==22) | .IpRanges[].CidrIp')
      do
        echo aws ec2 revoke-security-group-ingress --group-id "${group}" --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=${cidr}}]"
        aws ec2 revoke-security-group-ingress --group-id "${group}" --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=${cidr}}]"
      done
  done
