#!/bin/bash

ip=$(curl --silent https://checkip.amazonaws.com)
cidr="${ip}"/32


for group in $(aws ec2 describe-security-groups | jq -r '.SecurityGroups[].GroupId')
  do
    echo aws ec2 authorize-security-group-ingress --group-id "${group}" --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=${cidr}}]"
    aws ec2 authorize-security-group-ingress --group-id "${group}" --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=${cidr}}]"
  done
